# Generated by Django 5.0.3 on 2024-03-20 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_comment_options_book_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_active',
        ),
    ]
